services:
  primary-mysql:
    image: mysql:8.0
    container_name: primary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: delivery
    ports:
      - "3307:3306"
    volumes:
      - ./primary/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_primary_data:/var/lib/mysql

  secondary-mysql:
    image: mysql:8.0
    container_name: secondary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: delivery
    ports:
      - "3308:3306"
    depends_on:
      - primary-mysql
    volumes:
      - ./secondary/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./secondary/setup-replication.sh:/setup-replication.sh
      - mysql_secondary_data:/var/lib/mysql
    entrypoint: ["/bin/bash", "-c", "docker-entrypoint.sh mysqld & sleep 10 && bash /setup-replication.sh && wait"]

volumes:
  mysql_primary_data:
  mysql_secondary_data: